steps:
# This step install npm packages
- name: 'gcr.io/cloud-builders/npm'
  id: Install
  args: ['install']

# This step runs the unit tests on the app
- name: 'gcr.io/cloud-builders/npm'
  id: Test
  args: ['test']

